language: swift
xcode_project: GutenbergSem.xcodeproj
xcode_scheme: GutenbergSem
osx_image: xcode8.3
xcode_sdk: iphonesimulator10.0

script:
- xcodebuild clean build test -project GutenbergSem.xcodeproj -scheme GutenbergSem -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3'