language: objective-c
xcode_project: GutenbergSem.xcodeproj
xcode_scheme: GutenbergSemTests
osx_image: xcode8.3
xcode_sdk: iphonesimulator10.3


script:
- xcodebuild test -workspace GutenbergSem.xcworkspace -scheme GutenbergSem -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.3'

